version: '3.8'

services:
  mcp-router-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-router-proxy
    ports:
      - "80:80"
    volumes:
      - ./router_config.yaml:/root/router_config.yaml
    restart: unless-stopped
    environment:
      - GOTOOLCHAIN=auto
    networks:
      - mcp-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - mcp-network
    depends_on:
      - mcp-router-proxy

networks:
  mcp-network:
    driver: bridge