global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mcp-router-proxy'
    scrape_interval: 5s
    metrics_path: /metrics
    # If you're using basic auth, uncomment and configure these lines:
    basic_auth:
       username: 'admin'
       password: 'your_secure_password'
    static_configs:
      - targets: ['mcp-router-proxy:80'] 