# router_config.yaml
resources:
  # Route file resources to file service
  "^file://.*": "http://file-service:8080/rpc"
  # Route database resources to DB service
  "^db://.*": "http://database-service:8080/rpc"
  # Route API resources to API gateway
  "^api://.*": "http://api-gateway:8080/rpc"
  # Route S3 resources to storage service
  "^s3://.*": "http://storage-service:8080/rpc"
  "^weather/.*": "http://weather-service:8080/mcp"
  "^database/.*": "http://database-service:8080/mcp"

tools:
  # Route code generation tools to AI service
  "^code-.*": "http://ai-service:8080/rpc"
  # Route data processing tools to data service
  "^data-.*": "http://data-processing:8080/rpc"
  # Route search tools to search service
  "^search.*": "http://search-service:8080/rpc"
  # Route authentication tools to auth service
  "^auth.*": "http://auth-service:8080/rpc"
  "^calculator$": "http://calculator-service:8080/mcp"
  "^translator$": "http://translator-service:8080/mcp"

# Default service to route to if no patterns match
default: "http://default-service:8080/mcp"

# UI authentication settings
ui:
  username: "admin"
  password: "your_secure_password"

toolMappings:
  - originalName: "weather"
    targetName: "getWeather"
    target: "http://weather-service:8080/mcp"
  - originalName: "search"
    targetName: "googleSearch"
    target: "http://search-service:8080/mcp"
  