name: Go Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # Adjust this to your Go version

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...
